server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 90
spring:
  application:
    name: atlas-provider-user
  http:
#编码配置
    encoding:
      force: true
      charset : UTF-8
      enabled : true
  datasource:
#配置数据源
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///anytron?characterEncoding=utf8&useUnicode=true&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
#连接池的配置信息
## 初始化大小，最小，最大
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
## 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000
# 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000
# 配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      
mybatis:
  type-aliases-package: com.atlas.model
  mapper-locations: classpath:mapper/*/*.xml
  config-location: classpath:SqlMapConfig.xml
#mybatis
mapper:
  mappers: com.atlas.base.mapper.BaseMapper
  not-empty: false
   
#mappers 多个接口时逗号隔开
#pagehelper
pagehelper :
  offsetAsPageNum : true
  rowBoundsWithCount : true
  pageSizeZero : true
  reasonable : false
  supportMethodsArguments : false 
   
logging:
   config: classpath:log4j2.xml
   
   
   
