server:
  port: 8101
  tomcat:
    uri-encoding: UTF-8

#服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9001/eureka
    # 心跳检测检测与续约时间
    # 测试时将值设置设置小些，保证服务关闭后注册中心能及时踢出服务
  instance:
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（客户端告诉服务端自己会按照该规则）
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳之后等待的时间上限，单位为秒，超过则剔除（客户端告诉服务端按照此规则等待自己）
    lease-expiration-duration-in-seconds: 90
spring:
  application:
    name: atlas-consumer-client
  http:
#编码配置
    encoding:
      force: true
      charset : UTF-8
      enabled : true

feign:
  hystrix:
    enabled: true

logging:
   config: classpath:log4j2.xml
   
   
   
