server:
  port: 8101
  tomcat:
    uri-encoding: UTF-8

#服务注册到eureka地址
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9001/eureka
  instance:
    preferIpAddress : true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
spring:
  main: 
    allow-bean-definition-overriding: true
  application:
    name: atlas-consumer-client
  http:
#编码配置
    encoding:
      force: true
      charset : UTF-8
      enabled : true
  boot:
    admin:
      client:
        # 这个URL地址是SBA Server的服务地址，你需要将你的应用注册到该地址上
        url: http://localhost:9000
        # 配置连接到监测管理平台的Security安全密码
        username: admin
        password: admin
      
# 在默认情况下大多数Actuator的端点并没有完全公开，这里我将所有端点都进行公开进行管理
management.endpoints.web.exposure.include: "*"

feign:
  hystrix:
    enabled: true

logging:
   config: classpath:log4j2.xml
   
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
  
  
  
  
  
  
  
  
  